"""Backtest: replay the May 2024 Ahmedabad heatwave through the model (Phase 3, proposal §9.1).

References (see data/manual/backtest_event.md):
  A. IMD red alert for Ahmedabad, 20–24 May 2024.
  B. The Ahmedabad Heat Action Plan (2019) colour for each day, applied to the
     observed daily Tmax at the airport station (IMD 42647, Meteostat hourly).

Health outcomes are city-level only (69 heatstroke cases in May), so no
ward-level rank correlation is possible for this event.

Outputs in backtest/results/:
  may2024_wards.csv    one row per ward-day (pipeline.score_city schema)
  may2024_city.csv     one row per day: reference and model alert levels
  may2024_metrics.md   metrics tables
Usage:  python backtest/may2024.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from heatrisk import load_config  # noqa: E402
from heatrisk.pipeline import load_wards, score_city  # noqa: E402
from heatrisk.weather import fetch_archive  # noqa: E402

START, END = "2024-05-01", "2024-06-15"
IMD_RED = pd.date_range("2024-05-20", "2024-05-24")
STATION = ROOT / "data" / "raw" / "web" / "meteostat_42647.csv.gz"
OUT = Path(__file__).resolve().parent / "results"
LEVELS = ["green", "yellow", "orange", "red"]
# Ahmedabad Heat Action Plan 2019 colour signals (Tmax, °C) mapped onto the IMD colours used by the model
HAP_NAMES = {"green": "white (no alert)", "yellow": "yellow", "orange": "orange", "red": "red"}


def hap_level(tmax: float) -> str:
    if tmax >= 45.0:
        return "red"
    if tmax > 43.0:
        return "orange"
    if tmax > 41.0:
        return "yellow"
    return "green"


def station_tmax() -> pd.Series:
    """Daily max of the hourly station temperature, by local (IST) calendar day."""
    st = pd.read_csv(STATION, header=None, usecols=[0, 1, 2], names=["date", "hour", "temp"])
    st = st[(st.date >= "2024-04-30") & (st.date <= "2024-06-16")]
    idx = (pd.to_datetime(st.date) + pd.to_timedelta(st.hour, "h")).dt.tz_localize("UTC").dt.tz_convert("Asia/Kolkata")
    s = pd.Series(st.temp.to_numpy(), index=idx)
    g = s.groupby(s.index.date)
    daily = g.max()[g.size() >= 20]
    daily.index = pd.to_datetime(daily.index)
    return daily


def city_table(wards_table: pd.DataFrame) -> pd.DataFrame:
    t = wards_table.assign(lvl=wards_table["alert_mri"].map(LEVELS.index))
    g = t.groupby("date")
    city = pd.DataFrame({
        "model_max": g["lvl"].max().map(LEVELS.__getitem__),                  # worst ward
        "model_typical": g["mri"].median(),                                   # median ward MRI
        "n_orange_plus": g["lvl"].apply(lambda s: int((s >= 2).sum())),
        "n_red": g["lvl"].apply(lambda s: int((s == 3).sum())),
        "mri_min": g["mri"].min(), "mri_max": g["mri"].max(),
    })
    bands = load_config()["alerts"]["levels"]
    city["model_typical_level"] = [next(k for k, v in bands.items() if m <= v) for m in city["model_typical"]]
    tmax = station_tmax()
    city["station_tmax"] = tmax.reindex(city.index)
    city["hap_level"] = city["station_tmax"].map(lambda v: hap_level(v) if pd.notna(v) else None)
    city["imd_red"] = city.index.isin(IMD_RED)
    return city


def metrics(city: pd.DataFrame) -> str:
    lvl = city["model_max"].map(LEVELS.index)
    typ = city["model_typical_level"].map(LEVELS.index)
    lines = ["# May 2024 Backtest — Metrics", "",
             f"Window {START} to {END} ({len(city)} days), 48 wards. Generated by `backtest/may2024.py`.", ""]

    # A. IMD red alert window
    imd = city[city["imd_red"]]
    orange_run = lvl.ge(2)
    first = IMD_RED[0]
    lead = 0
    d = first - pd.Timedelta(days=1)
    while d in orange_run.index and orange_run[d]:
        lead += 1
        d -= pd.Timedelta(days=1)
    outside = city[~city["imd_red"]]
    lines += ["## A. Against the IMD red alert (20–24 May)", "",
              "| Metric | Value |", "|---|---|",
              f"| IMD red days with any ward at Orange or above | {int((imd['model_max'].map(LEVELS.index) >= 2).sum())} of {len(imd)} |",
              f"| IMD red days with any ward at Red | {int((imd['model_max'] == 'red').sum())} of {len(imd)} |",
              f"| IMD red days with the median ward at Red | {int((imd['model_typical_level'] == 'red').sum())} of {len(imd)} |",
              f"| Lead time: consecutive days at Orange+ before 20 May | {lead} |",
              f"| Days outside the IMD window with any ward at Red | {int((outside['model_max'] == 'red').sum())} of {len(outside)} "
              f"({', '.join(d.strftime('%d %b') for d in outside.index[outside['model_max'] == 'red']) or 'none'}) |",
              ""]

    # B. Daily agreement with the Heat Action Plan rule on observed Tmax
    ok = city.dropna(subset=["hap_level"])
    ref = ok["hap_level"].map(LEVELS.index)
    mod = ok["model_typical_level"].map(LEVELS.index)
    diff = mod - ref
    lines += ["## B. Daily agreement with the Heat Action Plan rule (median ward vs airport Tmax)", "",
              f"{len(ok)} days with complete station data.", "",
              "| Metric | Value |", "|---|---|",
              f"| Same level | {int((diff == 0).sum())} days ({(diff == 0).mean():.0%}) |",
              f"| Within one level | {int((diff.abs() <= 1).sum())} days ({(diff.abs() <= 1).mean():.0%}) |",
              f"| Model higher than the plan | {int((diff > 0).sum())} days |",
              f"| Model lower than the plan | {int((diff < 0).sum())} days |",
              f"| Plan Orange/Red days where the model is Orange/Red | {int(((ref >= 2) & (mod >= 2)).sum())} of {int((ref >= 2).sum())} |",
              f"| Plan Yellow/White days where the model is Orange/Red | {int(((ref <= 1) & (mod >= 2)).sum())} of {int((ref <= 1).sum())} |",
              "", "Rows: Heat Action Plan level from observed Tmax. Columns: model level for the median ward.", "",
              "| Plan \\ Model | " + " | ".join(LEVELS) + " |", "|---" * (len(LEVELS) + 1) + "|"]
    ct = pd.crosstab(ok["hap_level"], ok["model_typical_level"]).reindex(index=LEVELS, columns=LEVELS, fill_value=0)
    for r in LEVELS:
        lines.append(f"| {HAP_NAMES[r]} | " + " | ".join(str(ct.loc[r, c]) for c in LEVELS) + " |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    cfg, wards = load_config(), load_wards()
    c = cfg["city"]["centre"]
    wx = fetch_archive(c["lat"], c["lon"], START, END)
    table = score_city(wx, wards, cfg)
    city = city_table(table)

    OUT.mkdir(exist_ok=True)
    table.to_csv(OUT / "may2024_wards.csv", index=False)
    city.to_csv(OUT / "may2024_city.csv", index_label="date")
    text = metrics(city)
    (OUT / "may2024_metrics.md").write_text(text, encoding="utf-8")
    print(text)
    cols = ["station_tmax", "hap_level", "imd_red", "model_typical", "model_typical_level", "model_max", "n_red"]
    print(city[cols].round(1).to_string())


if __name__ == "__main__":
    main()
