"""Sensitivity analysis (Phase 3, proposal §9.3).

Re-scores the May 2024 peak (10–31 May) with one setting changed at a time and
compares the ward ranking — by mean MRI over the IMD window plus the days around it
(17–28 May) — against the baseline:

  • each HTSI indicator weight and each PVI weight × 0.8 and × 1.2 (others rescaled to sum to 1)
  • each HTSI extra (night, persistence) max points × 0.8 and × 1.2
  • downscaling beta_night 0, 0.15, 0.45, 0.6 and beta_day 0.3
  • risk vulnerability_spread 0.2, 0.3, 0.5, 0.6

Reports Spearman ρ against the baseline ranking, the largest rank move, and the
change in Red ward-days. Output: backtest/results/sensitivity.md
Usage:  python backtest/sensitivity.py
"""

from __future__ import annotations

import copy
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from heatrisk import load_config  # noqa: E402
from heatrisk.pipeline import load_wards, score_city  # noqa: E402
from heatrisk.weather import fetch_archive  # noqa: E402

START, END = "2024-05-10", "2024-05-31"
PEAK = ("2024-05-17", "2024-05-28")
OUT = Path(__file__).resolve().parent / "results"


def reweight(weights: dict, key: str, factor: float) -> dict:
    """Scale one weight and rescale the others so the total stays 1."""
    w = dict(weights)
    w[key] *= factor
    rest = sum(v for k, v in w.items() if k != key)
    target = 1.0 - w[key]
    return {k: (v if k == key else v * target / rest) for k, v in w.items()}


def scenarios(cfg: dict):
    for group, path in (("HTSI weight", ("thermal_stress", "weights")), ("PVI weight", ("pvi", "weights"))):
        weights = cfg[path[0]][path[1]]
        for key in weights:
            for f in (0.8, 1.2):
                c = copy.deepcopy(cfg)
                c[path[0]][path[1]] = reweight(weights, key, f)
                yield group, f"{key} ×{f}", c
    for extra in ("night", "persistence"):
        for f in (0.8, 1.2):
            c = copy.deepcopy(cfg)
            c["htsi"][extra]["max_points"] *= f
            if extra == "persistence":
                c["htsi"][extra]["points_per_day"] *= f
            yield "HTSI extra", f"{extra} points ×{f}", c
    for b in (0.0, 0.15, 0.45, 0.6):
        c = copy.deepcopy(cfg)
        c["downscaling"]["beta_night"] = b
        yield "Downscaling", f"beta_night = {b}", c
    c = copy.deepcopy(cfg)
    c["downscaling"]["beta_day"] = 0.3
    yield "Downscaling", "beta_day = 0.3", c
    for s in (0.2, 0.3, 0.5, 0.6):
        c = copy.deepcopy(cfg)
        c["risk"]["vulnerability_spread"] = s
        yield "Risk", f"vulnerability_spread = {s}", c


def summarize(table: pd.DataFrame) -> tuple[pd.Series, int]:
    peak = table[(table["date"] >= PEAK[0]) & (table["date"] <= PEAK[1])]
    return peak.groupby("ward_id")["mri"].mean(), int((table["alert_mri"] == "red").sum())


def main() -> None:
    cfg, wards = load_config(), load_wards()
    c = cfg["city"]["centre"]
    wx = fetch_archive(c["lat"], c["lon"], START, END)
    base_mri, base_red = summarize(score_city(wx, wards, cfg))
    base_rank = base_mri.rank(ascending=False)

    rows = []
    for group, name, scen_cfg in scenarios(cfg):
        mri, red = summarize(score_city(wx, wards, scen_cfg))
        rank = mri.rank(ascending=False)
        rows.append({"group": group, "change": name,
                     "spearman": base_mri.corr(mri, method="spearman"),
                     "max_rank_move": int((rank - base_rank).abs().max()),
                     "mean_mri_change": (mri - base_mri).mean(),
                     "red_ward_days": red, "red_change": red - base_red})
        print(f"{name:38s} rho={rows[-1]['spearman']:.3f}", flush=True)
    res = pd.DataFrame(rows)

    lines = ["# Sensitivity Analysis — May 2024", "",
             f"Ward ranking = mean MRI over {PEAK[0]} to {PEAK[1]}; Red ward-days counted over {START} to {END} "
             f"(baseline {base_red} of {len(wards) * len(pd.date_range(START, END))}). "
             "Generated by `backtest/sensitivity.py`.", "",
             "| Group | Change | Spearman ρ | Largest rank move | Mean MRI change | Red ward-days (Δ) |",
             "|---|---|---|---|---|---|"]
    for r in res.itertuples():
        flag = " ⚠️" if r.spearman < 0.8 else ""
        lines.append(f"| {r.group} | {r.change} | {r.spearman:.3f}{flag} | {r.max_rank_move} | "
                     f"{r.mean_mri_change:+.1f} | {r.red_ward_days} ({r.red_change:+d}) |")
    unstable = res[res["spearman"] < 0.8]
    lines += ["", f"Lowest ρ: {res['spearman'].min():.3f} ({res.loc[res['spearman'].idxmin(), 'change']}). "
              f"Changes with ρ < 0.8: {len(unstable)} of {len(res)}.", ""]
    OUT.mkdir(exist_ok=True)
    (OUT / "sensitivity.md").write_text("\n".join(lines), encoding="utf-8")
    res.to_csv(OUT / "sensitivity.csv", index=False)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
